# Generated by Django 2.0.4 on 2018-06-05 04:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.IntegerField(primary_key=1, serialize=False)),
                ('cate_parent_id', models.IntegerField()),
                ('cate_name', models.CharField(max_length=50)),
                ('cate_description', models.CharField(max_length=200)),
                ('cate_imgage', models.ImageField(null=True, upload_to='')),
                ('cate_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('new_id', models.AutoField(auto_created=1, primary_key=True, serialize=False)),
                ('new_name', models.CharField(max_length=100)),
                ('new_content', models.CharField(max_length=500, null=True)),
                ('new_text_position', models.CharField(max_length=50)),
                ('new_img', models.TextField()),
                ('new_date', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_saled', models.IntegerField(default=0)),
                ('product_favorited', models.IntegerField(default=0)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.BooleanField(default=1)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('product_detail_name', models.CharField(max_length=200)),
                ('product_detail_description', models.TextField(default='-', null=True)),
                ('product_detail_image', models.ImageField(null=True, upload_to='')),
                ('product_detail_price', models.IntegerField(default=0)),
                ('product_detail_discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('product_detail_quantity', models.IntegerField(default=0)),
                ('product_detail_date', models.DateTimeField(auto_now_add=True)),
                ('product_detail_saled', models.IntegerField(default=0)),
                ('product_detail_favorited', models.IntegerField(default=0)),
                ('product_detail_status', models.BooleanField(default=1)),
                ('cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('size_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagMap',
            fields=[
                ('tag_map_id', models.AutoField(auto_created=1, primary_key=True, serialize=False, unique=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProductDetail'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Size'),
        ),
    ]
