# Generated by Django 2.0.4 on 2018-06-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_id',
            field=models.AutoField(auto_created=1, primary_key=True, serialize=False),
        ),
    ]
